[package]
name = "nthash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert2 = "0.3.11"
fxhash = "0.2.1"
nthash = "0.5.1"
rayon = "1.8.0"
rdst = "0.20.12"
